// This file provides types for the API.
//
// Code generated by github.com/MarkRosemaker DO NOT EDIT.

package remoteokjobs

import (
	"net/url"
	"time"
)

// Jobs defines a model
type Jobs []Job

// Job defines a model
type Job struct {
	LastUpdated int        `json:"last_updated,omitzero"`
	Legal       string     `json:"legal,omitzero"`
	Slug        *string    `json:"slug,omitempty"`
	ID          *string    `json:"id,omitempty"`
	Epoch       *int       `json:"epoch,omitempty"`
	Date        *time.Time `json:"date,omitempty"`
	Company     *string    `json:"company,omitempty"`
	CompanyLogo *url.URL   `json:"company_logo,omitempty"`
	Position    *string    `json:"position,omitempty"`
	Tags        []string   `json:"tags,omitempty"`
	Description *string    `json:"description,omitempty"`
	Location    *string    `json:"location,omitempty"`
	SalaryMin   *int       `json:"salary_min,omitempty"`
	SalaryMax   *int       `json:"salary_max,omitempty"`
	ApplyURL    *url.URL   `json:"apply_url,omitempty"`
	Logo        *url.URL   `json:"logo,omitempty"`
	URL         *url.URL   `json:"url,omitempty"`
	Original    *bool      `json:"original,omitempty"`
	Verified    *bool      `json:"verified,omitempty"`
}
